name: Trigger auto deployment for aca-id-test3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/aca-id-test3-AutoDeployTrigger-65856d1b-0d63-424d-b1ce-ab124b629ac9.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAIDTEST3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: osslabacr.azurecr.io
          registryUsername: ${{ secrets.ACAIDTEST3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAIDTEST3_REGISTRY_PASSWORD }}
          containerAppName: aca-id-test3
          resourceGroup: RG-joaoribeiro
          imageToBuild: osslabacr.azurecr.io/aca-id-test3:${{ github.sha }}
          

     

