name: Trigger auto deployment for dgsnsgjsfj

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dgsnsgjsfj-AutoDeployTrigger-635b488e-dc8e-40cd-a397-92dce105cac7.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DGSNSGJSFJ_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: osslabacr.azurecr.io
          registryUsername: ${{ secrets.DGSNSGJSFJ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DGSNSGJSFJ_REGISTRY_PASSWORD }}
          containerAppName: dgsnsgjsfj
          resourceGroup: new-app-testoss
          imageToBuild: osslabacr.azurecr.io/dgsnsgjsfj:${{ github.sha }}
          

     

